### ISSUE TITLE
Extend it to work for Github as well?

### ISSUE THREAD

**Issue by kevinsamoei** [dann254/stack-overflow-padding#1]
Github has this problem as well on Pull Requests. When one makes a comment on a specific line of code it becomes really hard to read because of the scrollbar.

**Comment by dann254** [comment]
I had not noticed the same on GitHub. I'll see what I can do about that.
I might need to create a specific extension for GitHub.

**Comment by dann254** [comment]
here is a package that solves this 
https://github.com/dann254/octoscroll
https://github.com/dann254/octostack
